version: "3.3"

services:
  database:
    image: postgres
    container_name: postgres_bcb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bcb_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bcb_db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge
